name: 🚀 Release

on:
  push:
    branches:
      - master
    paths:
      - 'CHANGELOG.md'
      - '.changeset/**'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - run: pnpm install
      - run: pnpm run build
      - uses: changesets/action@v1
        with:
          publish: 'pnpm run release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}